### ISSUE TITLE
[RFC 0086] Guidelines for Accepting Component-level Contributions

### ISSUE THREAD

**Issue by hone** [buildpacks/community#93] opened 2021-05-13 20:54 UTC
Add the Guidelines from buildpacks/rfcs#143.

**Comment by samj1912** [comment] 2021-10-01 14:13
@sclevine are you still working on this?

**Comment by jjbustamante** [comment] 2022-11-04 19:48
@hone I think this issue can be closed, the PR that was intended to fix it was already merged :)

**Closed** 2022-11-05 15:49 UTC
